// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type AppliedTag struct {
	ID          []byte
	SampleID    []byte
	TagID       []byte
	DateAdded   sql.NullTime
	DateRemoved sql.NullTime
}

type Location struct {
	ID               []byte
	Name             string
	Description      sql.NullString
	ParentLocationID []byte
}

type Product struct {
	ID              []byte
	Name            string
	ParentProductID []byte
	PartNumber      sql.NullString
}

type Sample struct {
	ID             []byte
	LocationID     []byte
	ProductID      []byte
	TimeRegistered sql.NullTime
	LastUpdate     sql.NullTime
	State          string
	OwnerID        []byte
	ProductIssue   sql.NullString
}

type SampleComment struct {
	ID        []byte
	SampleID  []byte
	Comment   string
	CreatedAt sql.NullTime
}

type SampleMod struct {
	ID          []byte
	SampleID    []byte
	Name        string
	TimeAdded   time.Time
	TimeRemoved sql.NullTime
}

type SampleNote struct {
	ID       []byte
	SampleID []byte
	Contents string
	TimeMade time.Time
}

type Tag struct {
	ID        []byte
	Name      string
	Removable sql.NullBool
}

type User struct {
	ID   []byte
	Name string
}
