// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AppliedTag struct {
	ID          []byte
	SampleID    []byte
	TagID       []byte
	DateAdded   sql.NullTime
	DateRemoved sql.NullTime
}

type AuditLog struct {
	ID          int64
	ActorUserID sql.Null[[]byte]
	Action      string
	TargetType  string
	TargetID    sql.NullString
	Metadata    json.RawMessage
	CreatedAt   time.Time
}

type AuthChallenge struct {
	ChallengeToken string
	ChallengeBytes []byte
	UserID         sql.Null[[]byte]
	FlowType       string
	ExpiresAt      time.Time
	UsedAt         sql.NullTime
	CreatedAt      time.Time
}

type Location struct {
	ID               []byte
	Name             string
	Description      sql.NullString
	ParentLocationID sql.Null[[]byte]
}

type Passkey struct {
	ID           int64
	CredentialID []byte
	UserID       []byte
	PublicKey    []byte
	SignCounter  int64
	Transports   json.RawMessage
	Label        sql.NullString
	CreatedAt    time.Time
	RevokedAt    sql.NullTime
}

type PasskeyAssignmentLink struct {
	ID              int64
	TokenHash       string
	UserID          []byte
	CreatedByUserID sql.Null[[]byte]
	Purpose         string
	CreatedAt       time.Time
	ExpiresAt       sql.NullTime
	ConsumedAt      sql.NullTime
	RevokedAt       sql.NullTime
}

type Product struct {
	ID              []byte
	Name            string
	ParentProductID sql.Null[[]byte]
	PartNumber      sql.NullString
}

type Sample struct {
	ID             []byte
	LocationID     sql.Null[[]byte]
	ProductID      sql.Null[[]byte]
	TimeRegistered sql.NullTime
	LastUpdate     sql.NullTime
	State          string
	OwnerID        sql.Null[[]byte]
	ProductIssue   sql.NullString
}

type SampleComment struct {
	ID        []byte
	SampleID  []byte
	Comment   string
	CreatedAt sql.NullTime
}

type SampleMod struct {
	ID          []byte
	SampleID    []byte
	Name        string
	TimeAdded   time.Time
	TimeRemoved sql.NullTime
}

type SampleNote struct {
	ID       []byte
	SampleID []byte
	Contents string
	TimeMade time.Time
}

type Tag struct {
	ID        []byte
	Name      string
	Removable sql.NullBool
}

type User struct {
	ID   []byte
	Name string
}

type UserRole struct {
	UserID    []byte
	Role      string
	CreatedAt time.Time
}
