// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const addSampleMod = `-- name: AddSampleMod :exec
INSERT INTO
    sample_mods (id, sample_id, name, time_added, time_removed)
VALUES
    ($1, $2, $3, $4, NULL)
`

type AddSampleModParams struct {
	ID        []byte
	SampleID  []byte
	Name      string
	TimeAdded time.Time
}

func (q *Queries) AddSampleMod(ctx context.Context, arg AddSampleModParams) error {
	_, err := q.db.ExecContext(ctx, addSampleMod,
		arg.ID,
		arg.SampleID,
		arg.Name,
		arg.TimeAdded,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, roles, oidc_sid, refresh_token, access_token_expires_at, expires_at, id_token)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSessionParams struct {
	ID                   string
	UserID               []byte
	Roles                []string
	OidcSid              sql.NullString
	RefreshToken         sql.NullString
	AccessTokenExpiresAt time.Time
	ExpiresAt            time.Time
	IDToken              sql.NullString
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		pq.Array(arg.Roles),
		arg.OidcSid,
		arg.RefreshToken,
		arg.AccessTokenExpiresAt,
		arg.ExpiresAt,
		arg.IDToken,
	)
	return err
}

const deleteLocationByID = `-- name: DeleteLocationByID :exec
DELETE FROM locations
WHERE
    id = $1
`

func (q *Queries) DeleteLocationByID(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, deleteLocationByID, id)
	return err
}

const deleteProductByID = `-- name: DeleteProductByID :exec
DELETE FROM products
WHERE
    id = $1
`

func (q *Queries) DeleteProductByID(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, deleteProductByID, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionByOIDCSID = `-- name: DeleteSessionByOIDCSID :exec
DELETE FROM sessions WHERE oidc_sid = $1
`

func (q *Queries) DeleteSessionByOIDCSID(ctx context.Context, oidcSid sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByOIDCSID, oidcSid)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID []byte) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE
    id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const getLocation = `-- name: GetLocation :one
SELECT id, name, description, parent_location_id
FROM
    locations
WHERE
    id = $1
`

func (q *Queries) GetLocation(ctx context.Context, id []byte) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentLocationID,
	)
	return i, err
}

const getLocations = `-- name: GetLocations :many
SELECT id, name, description, parent_location_id
FROM
    locations
ORDER BY
    name
`

func (q *Queries) GetLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, getLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentLocationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, parent_product_id, part_number
FROM
    products
WHERE
    id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id []byte) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentProductID,
		&i.PartNumber,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT
    id, name, parent_product_id, part_number
FROM
    products
ORDER BY
    name
`

func (q *Queries) GetProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentProductID,
			&i.PartNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSampleById = `-- name: GetSampleById :one
SELECT
    id, location_id, product_id, time_registered, last_update, state, owner_id, product_issue
FROM
    samples
WHERE
    id = $1
`

func (q *Queries) GetSampleById(ctx context.Context, id []byte) (Sample, error) {
	row := q.db.QueryRowContext(ctx, getSampleById, id)
	var i Sample
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.ProductID,
		&i.TimeRegistered,
		&i.LastUpdate,
		&i.State,
		&i.OwnerID,
		&i.ProductIssue,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, roles, oidc_sid, refresh_token, access_token_expires_at, expires_at, created_at, id_token FROM sessions WHERE id = $1 AND expires_at > NOW()
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		pq.Array(&i.Roles),
		&i.OidcSid,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IDToken,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, oidc_sub
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.OidcSub)
	return i, err
}

const getUserByOIDCSub = `-- name: GetUserByOIDCSub :one
SELECT id, name, oidc_sub FROM users WHERE oidc_sub = $1
`

func (q *Queries) GetUserByOIDCSub(ctx context.Context, oidcSub sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByOIDCSub, oidcSub)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.OidcSub)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, oidc_sub
FROM
    users
ORDER BY
    name
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.OidcSub); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    id, name, parent_product_id, part_number
FROM
    products
ORDER BY
    name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentProductID,
			&i.PartNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSampleMods = `-- name: ListSampleMods :many
SELECT
    id, sample_id, name, time_added, time_removed
FROM
    sample_mods
WHERE
    sample_mods.sample_id = $1
ORDER BY
    time_added
`

func (q *Queries) ListSampleMods(ctx context.Context, sampleID []byte) ([]SampleMod, error) {
	rows, err := q.db.QueryContext(ctx, listSampleMods, sampleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SampleMod
	for rows.Next() {
		var i SampleMod
		if err := rows.Scan(
			&i.ID,
			&i.SampleID,
			&i.Name,
			&i.TimeAdded,
			&i.TimeRemoved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSamples = `-- name: ListSamples :many
SELECT
    samples.id, samples.location_id, samples.product_id, samples.time_registered, samples.last_update, samples.state, samples.owner_id, samples.product_issue,
    COALESCE(
        (
            SELECT
                STRING_AGG(sample_mods.name, ', ')
            FROM
                sample_mods
            WHERE
                sample_mods.sample_id = samples.id
                AND sample_mods.time_removed IS NULL
        ),
        ''
    ) AS current_mods_summary,
    users.name AS owner_name
FROM
    samples
LEFT JOIN users ON samples.owner_id = users.id
ORDER BY
    time_registered
`

type ListSamplesRow struct {
	ID                 []byte
	LocationID         sql.Null[[]byte]
	ProductID          sql.Null[[]byte]
	TimeRegistered     sql.NullTime
	LastUpdate         sql.NullTime
	State              string
	OwnerID            sql.Null[[]byte]
	ProductIssue       sql.NullString
	CurrentModsSummary interface{}
	OwnerName          sql.NullString
}

func (q *Queries) ListSamples(ctx context.Context) ([]ListSamplesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSamplesRow
	for rows.Next() {
		var i ListSamplesRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.ProductID,
			&i.TimeRegistered,
			&i.LastUpdate,
			&i.State,
			&i.OwnerID,
			&i.ProductIssue,
			&i.CurrentModsSummary,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSampleMod = `-- name: RemoveSampleMod :exec
UPDATE sample_mods
SET
    time_removed = $1
WHERE
    id = $2
`

type RemoveSampleModParams struct {
	TimeRemoved sql.NullTime
	ID          []byte
}

func (q *Queries) RemoveSampleMod(ctx context.Context, arg RemoveSampleModParams) error {
	_, err := q.db.ExecContext(ctx, removeSampleMod, arg.TimeRemoved, arg.ID)
	return err
}

const updateOrCreateSample = `-- name: UpdateOrCreateSample :one
INSERT INTO
    samples (
        id,
        location_id,
        product_id,
        time_registered,
        last_update,
        state,
        owner_id,
        product_issue
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT (id) DO
UPDATE
SET
    location_id = EXCLUDED.location_id,
    product_id = EXCLUDED.product_id,
    last_update = EXCLUDED.last_update,
    owner_id = EXCLUDED.owner_id,
    product_issue = EXCLUDED.product_issue,
    state = EXCLUDED.state RETURNING id, location_id, product_id, time_registered, last_update, state, owner_id, product_issue
`

type UpdateOrCreateSampleParams struct {
	ID             []byte
	LocationID     sql.Null[[]byte]
	ProductID      sql.Null[[]byte]
	TimeRegistered sql.NullTime
	LastUpdate     sql.NullTime
	State          string
	OwnerID        sql.Null[[]byte]
	ProductIssue   sql.NullString
}

func (q *Queries) UpdateOrCreateSample(ctx context.Context, arg UpdateOrCreateSampleParams) (Sample, error) {
	row := q.db.QueryRowContext(ctx, updateOrCreateSample,
		arg.ID,
		arg.LocationID,
		arg.ProductID,
		arg.TimeRegistered,
		arg.LastUpdate,
		arg.State,
		arg.OwnerID,
		arg.ProductIssue,
	)
	var i Sample
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.ProductID,
		&i.TimeRegistered,
		&i.LastUpdate,
		&i.State,
		&i.OwnerID,
		&i.ProductIssue,
	)
	return i, err
}

const updateSessionTokens = `-- name: UpdateSessionTokens :exec
UPDATE sessions
SET refresh_token = $2, access_token_expires_at = $3
WHERE id = $1
`

type UpdateSessionTokensParams struct {
	ID                   string
	RefreshToken         sql.NullString
	AccessTokenExpiresAt time.Time
}

func (q *Queries) UpdateSessionTokens(ctx context.Context, arg UpdateSessionTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTokens, arg.ID, arg.RefreshToken, arg.AccessTokenExpiresAt)
	return err
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users
SET
    name = $2
WHERE
    id = $1
`

type UpdateUserParams struct {
	ID   []byte
	Name string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUser, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertLocation = `-- name: UpsertLocation :exec
INSERT INTO
    locations (id, name, description, parent_location_id)
VALUES
    ($1, $2, $3, $4) ON CONFLICT (id) DO
UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    parent_location_id = EXCLUDED.parent_location_id
`

type UpsertLocationParams struct {
	ID               []byte
	Name             string
	Description      sql.NullString
	ParentLocationID sql.Null[[]byte]
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertLocation,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentLocationID,
	)
	return err
}

const upsertProduct = `-- name: UpsertProduct :exec
INSERT INTO
    products (id, name, parent_product_id, part_number)
VALUES
    ($1, $2, $3, $4) ON CONFLICT (id) DO
UPDATE
SET
    name = EXCLUDED.name,
    parent_product_id = EXCLUDED.parent_product_id,
    part_number = EXCLUDED.part_number
`

type UpsertProductParams struct {
	ID              []byte
	Name            string
	ParentProductID sql.Null[[]byte]
	PartNumber      sql.NullString
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) error {
	_, err := q.db.ExecContext(ctx, upsertProduct,
		arg.ID,
		arg.Name,
		arg.ParentProductID,
		arg.PartNumber,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO
    users (id, name)
VALUES
    ($1, $2) ON CONFLICT (id) DO
UPDATE
SET
    name = EXCLUDED.name
`

type UpsertUserParams struct {
	ID   []byte
	Name string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser, arg.ID, arg.Name)
	return err
}

const upsertUserByOIDCSub = `-- name: UpsertUserByOIDCSub :one
INSERT INTO users (id, name, oidc_sub)
VALUES ($1, $2, $3)
ON CONFLICT (oidc_sub) WHERE oidc_sub IS NOT NULL DO UPDATE
SET name = EXCLUDED.name
RETURNING id, name, oidc_sub
`

type UpsertUserByOIDCSubParams struct {
	ID      []byte
	Name    string
	OidcSub sql.NullString
}

func (q *Queries) UpsertUserByOIDCSub(ctx context.Context, arg UpsertUserByOIDCSubParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByOIDCSub, arg.ID, arg.Name, arg.OidcSub)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.OidcSub)
	return i, err
}
