CREATE TABLE IF NOT EXISTS users (
    id BYTEA PRIMARY KEY NOT NULL,
    name VARCHAR(100) NOT NULL
);

ALTER TABLE samples
ADD COLUMN owner_id BYTEA REFERENCES users (id);

ALTER TABLE samples
ADD COLUMN product_issue VARCHAR(4);

ALTER TABLE products ADD COLUMN part_number VARCHAR(64);

CREATE TABLE IF NOT EXISTS sample_comments (
    id BYTEA PRIMARY KEY NOT NULL,
    sample_id BYTEA NOT NULL REFERENCES samples (id),
    comment TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tags (
    id BYTEA PRIMARY KEY NOT NULL,
    name VARCHAR(64) NOT NULL UNIQUE,
    removable BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS applied_tags (
    id BYTEA PRIMARY KEY NOT NULL,
    sample_id BYTEA NOT NULL REFERENCES samples (id),
    tag_id BYTEA NOT NULL REFERENCES tags (id),
    date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_removed TIMESTAMP DEFAULT NULL
);