name: Build and Distribute Sample Tracker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Build Frontend
        run: |
          cd client
          bun install
          bun run build --emptyOutDir
      - name: Upload Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: build/client/**

  build-linux:
    needs: build-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Frontend Build
        uses: actions/download-artifact@v4
        with:
          name: client-build
          path: build/client
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Build Linux binary
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/reesource-tracker ./main.go
      - name: Remove existing build/database directory
        run: rm -rf build/database
      - name: Create build/database directory
        run: mkdir -p build/database
      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: reesource-tracker-linux
          path: build/**

  build-windows:
    needs: build-client
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Frontend Build
        uses: actions/download-artifact@v4
        with:
          name: client-build
          path: build/client
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Build Windows binary
        run: |
          $env:GOOS='windows'
          $env:GOARCH='amd64'
          go build -o build/reesource-tracker.exe ./main.go
      - name: Remove existing build/database directory
        run: if (Test-Path "build/database") { Remove-Item -Recurse -Force "build/database" }
      - name: Create build/database directory
        run: mkdir build/database
      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: reesource-tracker-windows
          path: build/**

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: sample-tracker:latest
          outputs: type=docker
      - name: Create build directory
        run: mkdir -p build
      - name: Save Docker image as tar
        run: docker save sample-tracker:latest -o build/sample-tracker-docker.tar
      - name: Upload Docker image tar
        uses: actions/upload-artifact@v4
        with:
          name: sample-tracker-docker
          path: build/reesource-tracker-docker.tar
